import { defineConfig } from 'tsup'

export default defineConfig({
  entry: {
    'core/types': 'src/interactive-os/core/types.ts',
    'core/createStore': 'src/interactive-os/core/createStore.ts',
    'core/createCommandEngine': 'src/interactive-os/core/createCommandEngine.ts',
    'plugins/core': 'src/interactive-os/plugins/core.ts',
    'plugins/history': 'src/interactive-os/plugins/history.ts',
    'plugins/crud': 'src/interactive-os/plugins/crud.ts',
    'plugins/clipboard': 'src/interactive-os/plugins/clipboard.ts',
    'plugins/rename': 'src/interactive-os/plugins/rename.ts',
    'plugins/dnd': 'src/interactive-os/plugins/dnd.ts',
    'behaviors/types': 'src/interactive-os/behaviors/types.ts',
    'behaviors/treegrid': 'src/interactive-os/behaviors/treegrid.ts',
    'behaviors/listbox': 'src/interactive-os/behaviors/listbox.ts',
    'behaviors/disclosure': 'src/interactive-os/behaviors/disclosure.ts',
    'behaviors/tabs': 'src/interactive-os/behaviors/tabs.ts',
    'behaviors/accordion': 'src/interactive-os/behaviors/accordion.ts',
    'behaviors/menu': 'src/interactive-os/behaviors/menu.ts',
    'behaviors/dialog': 'src/interactive-os/behaviors/dialog.ts',
    'behaviors/toolbar': 'src/interactive-os/behaviors/toolbar.ts',
    'behaviors/grid': 'src/interactive-os/behaviors/grid.ts',
    'behaviors/combobox': 'src/interactive-os/behaviors/combobox.ts',
    'behaviors/radiogroup': 'src/interactive-os/behaviors/radiogroup.ts',
    'behaviors/slider': 'src/interactive-os/behaviors/slider.ts',
    'behaviors/spinbutton': 'src/interactive-os/behaviors/spinbutton.ts',
    'behaviors/alertdialog': 'src/interactive-os/behaviors/alertdialog.ts',
    'behaviors/switch': 'src/interactive-os/behaviors/switch.ts',
    'behaviors/tree': 'src/interactive-os/behaviors/tree.ts',
    'behaviors/createBehaviorContext': 'src/interactive-os/behaviors/createBehaviorContext.ts',
    'plugins/combobox': 'src/interactive-os/plugins/combobox.ts',
    'plugins/focusRecovery': 'src/interactive-os/plugins/focusRecovery.ts',
    'hooks/useAria': 'src/interactive-os/hooks/useAria.ts',
    'hooks/useControlledAria': 'src/interactive-os/hooks/useControlledAria.ts',
    'hooks/useKeyboard': 'src/interactive-os/hooks/useKeyboard.ts',
    'components/aria': 'src/interactive-os/components/aria.tsx',
    'components/AriaInternalContext': 'src/interactive-os/components/AriaInternalContext.ts',
    'ui/TreeGrid': 'src/interactive-os/ui/TreeGrid.tsx',
    'ui/ListBox': 'src/interactive-os/ui/ListBox.tsx',
    'ui/TabList': 'src/interactive-os/ui/TabList.tsx',
    'ui/Accordion': 'src/interactive-os/ui/Accordion.tsx',
    'ui/MenuList': 'src/interactive-os/ui/MenuList.tsx',
    'ui/DisclosureGroup': 'src/interactive-os/ui/DisclosureGroup.tsx',
    'ui/Grid': 'src/interactive-os/ui/grid.tsx',
    'ui/Combobox': 'src/interactive-os/ui/combobox.tsx',
    'ui/RadioGroup': 'src/interactive-os/ui/radiogroup.tsx',
    'ui/SwitchGroup': 'src/interactive-os/ui/SwitchGroup.tsx',
    'ui/TreeView': 'src/interactive-os/ui/TreeView.tsx',
    'ui/Slider': 'src/interactive-os/ui/Slider.tsx',
    'ui/Spinbutton': 'src/interactive-os/ui/Spinbutton.tsx',
    'axes/value': 'src/interactive-os/axes/value.ts',
  },
  format: ['esm'],
  dts: true,
  splitting: true,
  clean: true,
  outDir: 'dist-lib',
  external: ['react', 'react-dom'],
  treeshake: true,
  tsconfig: 'tsconfig.app.json',
  esbuildOptions(options) {
    options.jsx = 'automatic'
  },
})
