import { defineConfig } from 'tsup'

export default defineConfig({
  entry: {
    'store/types': 'src/interactive-os/store/types.ts',
    'store/createStore': 'src/interactive-os/store/createStore.ts',
    'engine/createCommandEngine': 'src/interactive-os/engine/createCommandEngine.ts',
    'plugins/core': 'src/interactive-os/plugins/core.ts',
    'plugins/history': 'src/interactive-os/plugins/history.ts',
    'plugins/crud': 'src/interactive-os/plugins/crud.ts',
    'plugins/clipboard': 'src/interactive-os/plugins/clipboard.ts',
    'plugins/rename': 'src/interactive-os/plugins/rename.ts',
    'plugins/dnd': 'src/interactive-os/plugins/dnd.ts',
    'plugins/combobox': 'src/interactive-os/plugins/combobox.ts',
    'plugins/focusRecovery': 'src/interactive-os/plugins/focusRecovery.ts',
    'pattern/types': 'src/interactive-os/pattern/types.ts',
    'pattern/treegrid': 'src/interactive-os/pattern/treegrid.ts',
    'pattern/listbox': 'src/interactive-os/pattern/listbox.ts',
    'pattern/disclosure': 'src/interactive-os/pattern/disclosure.ts',
    'pattern/tabs': 'src/interactive-os/pattern/tabs.ts',
    'pattern/accordion': 'src/interactive-os/pattern/accordion.ts',
    'pattern/menu': 'src/interactive-os/pattern/menu.ts',
    'pattern/dialog': 'src/interactive-os/pattern/dialog.ts',
    'pattern/toolbar': 'src/interactive-os/pattern/toolbar.ts',
    'pattern/grid': 'src/interactive-os/pattern/grid.ts',
    'pattern/combobox': 'src/interactive-os/pattern/combobox.ts',
    'pattern/radiogroup': 'src/interactive-os/pattern/radiogroup.ts',
    'pattern/slider': 'src/interactive-os/pattern/slider.ts',
    'pattern/spinbutton': 'src/interactive-os/pattern/spinbutton.ts',
    'pattern/alertdialog': 'src/interactive-os/pattern/alertdialog.ts',
    'pattern/switch': 'src/interactive-os/pattern/switch.ts',
    'pattern/tree': 'src/interactive-os/pattern/tree.ts',
    'pattern/createPatternContext': 'src/interactive-os/pattern/createPatternContext.ts',
    'primitives/useAria': 'src/interactive-os/primitives/useAria.ts',
    'primitives/useControlledAria': 'src/interactive-os/primitives/useControlledAria.ts',
    'primitives/useKeyboard': 'src/interactive-os/primitives/useKeyboard.ts',
    'primitives/aria': 'src/interactive-os/primitives/aria.tsx',
    'primitives/AriaInternalContext': 'src/interactive-os/primitives/AriaInternalContext.ts',
    'ui/TreeGrid': 'src/interactive-os/ui/TreeGrid.tsx',
    'ui/ListBox': 'src/interactive-os/ui/ListBox.tsx',
    'ui/TabList': 'src/interactive-os/ui/TabList.tsx',
    'ui/Accordion': 'src/interactive-os/ui/Accordion.tsx',
    'ui/MenuList': 'src/interactive-os/ui/MenuList.tsx',
    'ui/DisclosureGroup': 'src/interactive-os/ui/DisclosureGroup.tsx',
    'ui/Grid': 'src/interactive-os/ui/Grid.tsx',
    'ui/Combobox': 'src/interactive-os/ui/Combobox.tsx',
    'ui/RadioGroup': 'src/interactive-os/ui/RadioGroup.tsx',
    'ui/SwitchGroup': 'src/interactive-os/ui/SwitchGroup.tsx',
    'ui/TreeView': 'src/interactive-os/ui/TreeView.tsx',
    'ui/Slider': 'src/interactive-os/ui/Slider.tsx',
    'ui/Spinbutton': 'src/interactive-os/ui/Spinbutton.tsx',
    'axis/value': 'src/interactive-os/axis/value.ts',
  },
  format: ['esm'],
  dts: true,
  splitting: true,
  clean: true,
  outDir: 'dist-lib',
  external: ['react', 'react-dom'],
  treeshake: true,
  tsconfig: 'tsconfig.app.json',
  esbuildOptions(options) {
    options.jsx = 'automatic'
  },
})
