#!/usr/bin/env node
import { writeFileSync } from 'fs'
import { execSync } from 'child_process'
import path from 'path'
import { readRegistry, cleanStale } from '../.claude/hooks/worktreeRegistry.mjs'

const gitCommonDir = execSync('git rev-parse --git-common-dir', { encoding: 'utf8' }).trim()
const absCommonDir = path.isAbsolute(gitCommonDir) ? gitCommonDir : path.resolve(gitCommonDir)
const repoRoot = path.dirname(absCommonDir)
const CADDYFILE = path.join(repoRoot, '.claude', 'Caddyfile')
const GATEWAY_PORT = Number(process.env.WT_GATEWAY_PORT ?? 4100)
const DASH_PORT = Number(process.env.WT_DASH_PORT ?? 4000)

cleanStale()
const entries = readRegistry()

const header = `# AUTO-GENERATED by scripts/wtCaddy.mjs — do not edit.
# Reload: caddy reload --config .claude/Caddyfile --adapter caddyfile

{
  auto_https off
  admin localhost:2019
}

# Dashboard — http://wt.localhost:${GATEWAY_PORT}
http://wt.localhost:${GATEWAY_PORT} {
  reverse_proxy localhost:${DASH_PORT}
}
`

const blocks = entries
  .filter((e) => e.port)
  .map((e) => `# ${e.branch}
http://${e.name}.localhost:${GATEWAY_PORT} {
  reverse_proxy localhost:${e.port}
}`)
  .join('\n\n')

writeFileSync(CADDYFILE, header + '\n' + blocks + '\n')
process.stdout.write(`wrote ${CADDYFILE} (${entries.length} worktree${entries.length === 1 ? '' : 's'})\n`)

if (process.argv.includes('--reload')) {
  try {
    execSync(`caddy reload --config ${CADDYFILE} --adapter caddyfile`, { stdio: 'inherit' })
  } catch {
    process.stderr.write('caddy reload 실패. caddy 실행 중인지 확인: pnpm wt:gateway\n')
  }
}
